FROM easypi/alpine-arm

RUN apk add --update python py-pip

ADD *.py /src/
ADD requirements.txt /src/

WORKDIR /src
RUN pip install -r requirements.txt
CMD ["python", "cashbot.py", "/config/config.yml"]
